#! /usr/bin/env python3


# paj-fetcher -- Download and convert data from PAJ
# By: Evgeniy Smirnov <rassouljb@gmail.com>
#
# Copyright (C) 2020 Cepremap
# https://git.nomics.world/dbnomics-fetchers/paj-fetcher
#
# paj-fetcher is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# paj-fetcher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


"""Convert data from PAJ to DBnomics data model
(see https://git.nomics.world/dbnomics/dbnomics-data-model/).

Usage:
    {self_filename} <source_dir> <target_dir> [options]

source_dir: path of source directory containing World Bank series generated by
            download.py script
target_dir: path of target directory to write datasets & series in DBnomics format
            => all files will be deleted

Options:
    --debug show debug output, and compute some tests that makes process slower

Read source data from a source directory, write converted data to a target directory.

See also `.gitlab-ci.yml` in which data is committed to a Git repository of converted
 data.
"""

import argparse
import json
import logging
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Sequence

import xlrd
from dbnomics_fetcher_toolbox.arguments import add_arguments_for_convert
from dbnomics_fetcher_toolbox.logging_utils import setup_logging
from dbnomics_fetcher_toolbox.sdmx_v2_0 import AttachmentLevel, Attribute, Code, \
    CodeList, Concept, DatasetStructure, Dimension, Obs, Series, Value, \
    parse_observation_value, NAN, structure_to_dataset_json, series_to_series_json
from dbnomics_json_errors import ErrorsArtifact

PROVIDER_DATA = {
    "code": "paj",
    "name": "Petroleum Association of Japan",
    "region": "Japan",
    "terms_of_use": "",
    "website": "https://www.paj.gr.jp/english/statis/",
}

attributes = {'UNIT': Attribute(concept_id="UNIT", codelist_id="CL_UNIT",
                                attachment_level=AttachmentLevel.SERIES)}
codelists = {"CL_UNIT": CodeList(id="CL_UNIT",
                                 codes=[Code(value="kl",
                                             descriptions={"en": "Kiloliter"}),
                                        Code(value="ton",
                                             descriptions={"en": "Ton"}),
                                        Code(value="Yen/kl",
                                             descriptions={"en": "Yen for kiloliter"}),
                                        Code(value="Yen/ton",
                                             descriptions={"en": "Yen for ton"}),
                                        Code(value="Dol/kl",
                                             descriptions={
                                                 "en": "Dollars for kiloliter"}),
                                        Code(value="Dol/ton",
                                             descriptions={"en": "Dollars for ton"}),
                                        Code(value="10k_kls",
                                             descriptions={"en": "10 thousand kls"})
                                        ],
                                 names={"en": "Unit of measure"}),
             "CL_FREQ": CodeList(id="CL_FREQ",
                                 codes=[
                                     Code(value="M", descriptions={"en": "Monthly"})],
                                 names={"en": "Frequency"}),
             "CL_COUNTRY": CodeList(id="CL_COUNTRY",
                                    codes=[Code(value="AE",
                                                descriptions={
                                                    "en": "United Arab Emirates"}),
                                           Code(value="AO",
                                                descriptions={"en": "Angola"}),
                                           Code(value="AU",
                                                descriptions={"en": "Australia"}),
                                           Code(value="BH",
                                                descriptions={"en": "Bahrain"}),
                                           Code(value="BN",
                                                descriptions={"en": "Brunei"}),
                                           Code(value="CA",
                                                descriptions={"en": "Canada"}),
                                           Code(value="CH",
                                                descriptions={"en": "China"}),
                                           Code(value="CM",
                                                descriptions={"en": "Cameroon"}),
                                           Code(value="CO",
                                                descriptions={"en": "Colombia"}),
                                           Code(value="DZ",
                                                descriptions={"en": "Algeria"}),
                                           Code(value="EC",
                                                descriptions={"en": "Ecuador"}),
                                           Code(value="EG",
                                                descriptions={"en": "Egypt"}),
                                           Code(value="ES",
                                                descriptions={"en": "Spain"}),
                                           Code(value="GA",
                                                descriptions={"en": "Gabon"}),
                                           Code(value="GR",
                                                descriptions={"en": "Greece"}),
                                           Code(value="HK",
                                                descriptions={"en": "HongKong"}),
                                           Code(value="ID",
                                                descriptions={"en": "Indonesia"}),
                                           Code(value="IN",
                                                descriptions={"en": "India"}),
                                           Code(value="IR",
                                                descriptions={"en": "Iran"}),
                                           Code(value="KR",
                                                descriptions={"en": "South Korea"}),
                                           Code(value="KW",
                                                descriptions={"en": "Kuwait"}),
                                           Code(value="KZ",
                                                descriptions={"en": "Kazakhstan"}),
                                           Code(value="LK",
                                                descriptions={"en": "Sri Lanka"}),
                                           Code(value="LY",
                                                descriptions={"en": "Libya"}),
                                           Code(value="MX",
                                                descriptions={"en": "Mexico"}),
                                           Code(value="MY",
                                                descriptions={"en": "Malaysia"}),
                                           Code(value="NO",
                                                descriptions={"en": "Norway"}),
                                           Code(value="OM",
                                                descriptions={"en": "Oman"}),
                                           Code(value="PE",
                                                descriptions={"en": "Peru"}),
                                           Code(value="PG",
                                                descriptions={
                                                    "en": "Papua New Guinea"}),
                                           Code(value="PK",
                                                descriptions={"en": "Pakistan"}),
                                           Code(value="PL",
                                                descriptions={"en": "Poland"}),
                                           Code(value="QA",
                                                descriptions={"en": "Qatar"}),
                                           Code(value="RU",
                                                descriptions={"en": "Russia"}),
                                           Code(value="SA",
                                                descriptions={"en": "Saudi Arabia"}),
                                           Code(value="SG",
                                                descriptions={"en": "Singapore"}),
                                           Code(value="TH",
                                                descriptions={"en": "Thailand"}),
                                           Code(value="TW",
                                                descriptions={"en": "Taiwan"}),
                                           Code(value="VN",
                                                descriptions={"en": "Vietnam"}),
                                           Code(value="US",
                                                descriptions={
                                                    "en": "United States of America"}),
                                           Code(value="UNK",
                                                descriptions={"en": "Unknown"})],
                                    names={"en": "Country"}),
             "CL_PRODUCT": CodeList(id="CL_PRODUCT",
                                    codes=[Code(value="A",
                                                descriptions={"en": "Asphalt"}),
                                           Code(value="CO",
                                                descriptions={"en": "Crude Oil"}),
                                           Code(value="FOA",
                                                descriptions={"en": "Fuel Oil A"}),
                                           Code(value="FOBC",
                                                descriptions={"en": "Fuel Oil B-C"}),
                                           Code(value="FOC",
                                                descriptions={"en": "Fuel Oil C"}),
                                           Code(value="G",
                                                descriptions={"en": "Gasoline"}),
                                           Code(value="GO",
                                                descriptions={"en": "Gas Oil"}),
                                           Code(value="JF",
                                                descriptions={"en": "Jet Fuel"}),
                                           Code(value="K",
                                                descriptions={"en": "Kerosene"}),
                                           Code(value="LPG",
                                                descriptions={"en": "LPG"}),
                                           Code(value="LO",
                                                descriptions={"en": "Lubricating Oil"}),
                                           Code(value="N",
                                                descriptions={"en": "Naphtha"}),
                                           Code(value="P",
                                                descriptions={"en": "Paraffin"})],
                                    names={"en": "Product"}),
             "CL_CURRENCY": CodeList(id="CL_CURRENCY",
                                     codes=[Code(value="Y", descriptions={"en": "Yen"}),
                                            Code(value="D",
                                                 descriptions={"en": "Dollar"})],
                                     names={"en": "Currency"}),
             "CL_INDEX": CodeList(id="CL_INDEX",
                                  codes=[Code(value="RP",
                                              descriptions={
                                                  "en": "Refinery production"}),
                                         Code(value="P",
                                              descriptions={"en": "Product"}),
                                         Code(value="I", descriptions={"en": "Import"}),
                                         Code(value="TS",
                                              descriptions={"en": "Total Supply"}),
                                         Code(value="S",
                                              descriptions={"en": "Sales"}),
                                         Code(value="OU",
                                              descriptions={"en": "Own use"}),
                                         Code(value="E",
                                              descriptions={"en": "Export"}),
                                         Code(value="TD",
                                              descriptions={"en": "Total Demand"}),
                                         Code(value="ES",
                                              descriptions={"en": "End stocks"})],
                                  names={"en": "Measurement index"})
             }
concepts = {"UNIT": Concept(id="UNIT", names={"en": "Unit of measure"}),
            "FREQ": Concept(id="FREQ", names={"en": "Frequency"}),
            "COUNTRY": Concept(id="COUNTRY", names={"en": "Country"}),
            "PRODUCT": Concept(id="PRODUCT", names={"en": "Product"}),
            "CURRENCY": Concept(id="CURRENCY", names={"en": "Currency"}),
            "INDEX": Concept(id="INDEX", names={"en": "Index of measurements"})
            }

DATASETS_DEFINITIONS = {
    "01": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   CodeList(id="CL_INDEX",
                            codes=[Code(value="P", descriptions={"en": "Production"}),
                                   Code(value="I", descriptions={"en": "Import"}),
                                   Code(value="NRU",
                                        descriptions={"en": "non-Refining use"}),
                                   Code(value="RT",
                                        descriptions={"en": "Refinery throughput"}),
                                   Code(value="BD", descriptions={"en": "(b/ｄ)"}),
                                   Code(value="RC",
                                        descriptions={"en": "Refining capacity"}),
                                   Code(value="U", descriptions={"en": "Utilization"}),
                                   Code(value="ES", descriptions={"en": "End stocks"})],
                            names={"en": "Measurement index"})],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  concepts["INDEX"]],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="INDEX", codelist_id="CL_INDEX")],
        id="SDCO",
        names={"en": "Supply and Demand of Crude Oil"})],
    "02": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   codelists["CL_INDEX"],
                   codelists["CL_PRODUCT"]],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  concepts["INDEX"],
                  concepts["PRODUCT"]],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="INDEX", codelist_id="CL_INDEX"),
                    Dimension(concept_id="PRODUCT", codelist_id="CL_PRODUCT")],
        id="SaDoPP",
        names={"en": "Supply and Demand of Petroleum Product"}
    )],
    "03": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   codelists["CL_COUNTRY"],
                   codelists["CL_PRODUCT"]],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  concepts["COUNTRY"],
                  concepts["PRODUCT"]],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="PRODUCT", codelist_id="CL_PRODUCT"),
                    Dimension(concept_id="COUNTRY", codelist_id="CL_COUNTRY")],
        id="PIbC",
        names={"en": "Product Import by Countries"}
    )],
    "04": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   codelists["CL_COUNTRY"]],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  concepts["COUNTRY"]],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="COUNTRY", codelist_id="CL_COUNTRY")],
        id="COIbC",
        names={"en": "Crude Oil Import by Country"}),
        DatasetStructure(
            attributes=[attributes['UNIT']],
            codelists=[codelists["CL_UNIT"],
                       codelists["CL_FREQ"],
                       CodeList(id="CL_OILTYPE",
                                codes=[
                                    Code(value="CB", descriptions={"en": "Cpc-B"}),
                                    Code(value="BH", descriptions={"en": "Bach Ho"}),
                                    Code(value="DH", descriptions={"en": "Dai Hung"}),
                                    Code(value="RUB", descriptions={"en": "Ruby"}),
                                    Code(value="SUT", descriptions={"en": "Sutuden"}),
                                    Code(value="CS", descriptions={"en": "Chim-Sao"}),
                                    Code(value="DUL", descriptions={"en": "Dulang"}),
                                    Code(value="PB", descriptions={"en": "Penara-B"}),
                                    Code(value="SEP", descriptions={"en": "Sepat"}),
                                    Code(value="MF", descriptions={"en": "Mysia-FO"}),
                                    Code(value="BER", descriptions={"en": "Bertam"}),
                                    Code(value="BF", descriptions={"en": "BLEND-FO"}),
                                    Code(value="LS", descriptions={"en": "L-Seria"}),
                                    Code(value="CHA", descriptions={"en": "Champion"}),
                                    Code(value="SL", descriptions={"en": "Sumatr-L"}),
                                    Code(value="KAJ", descriptions={"en": "Kajisemo"}),
                                    Code(value="KET", descriptions={"en": "Ketapang"}),
                                    Code(value="IL", descriptions={"en": "Iran-L"}),
                                    Code(value="IH", descriptions={"en": "Iran-H"}),
                                    Code(value="FB", descriptions={"en": "Forozn-B"}),
                                    Code(value="SPC", descriptions={"en": "S-Pars-C"}),
                                    Code(value="SOR", descriptions={"en": "Soroosh"}),
                                    Code(value="BASL", descriptions={"en": "Basrah-L"}),
                                    Code(value="BASH", descriptions={"en": "Basrah-H"}),
                                    Code(value="BAM", descriptions={"en": "Banoc-AM"}),
                                    Code(value="AL", descriptions={"en": "Arab-L"}),
                                    Code(value="AH", descriptions={"en": "Arab-H"}),
                                    Code(value="AM", descriptions={"en": "Arab-M"}),
                                    Code(value="AEL", descriptions={"en": "Arab-E-L"}),
                                    Code(value="ASL", descriptions={"en": "Arab-S-L"}),
                                    Code(value="KUW", descriptions={"en": "Kuwait"}),
                                    Code(value="KSL", descriptions={"en": "Kwait-SL"}),
                                    Code(value="Q", descriptions={"en": "Qatar"}),
                                    Code(value="QM", descriptions={"en": "Qatar-M"}),
                                    Code(value="AS", descriptions={"en": "A-Shahen"}),
                                    Code(value="LC", descriptions={"en": "Lowsul-C"}),
                                    Code(value="DFC", descriptions={"en": "Deod-F-C"}),
                                    Code(value="OM", descriptions={"en": "Oman"}),
                                    Code(value="MUR", descriptions={"en": "Murban"}),
                                    Code(value="DUB", descriptions={"en": "Dubai"}),
                                    Code(value="UZ", descriptions={"en": "U-Zakum"}),
                                    Code(value="DAS", descriptions={"en": "DAS"}),
                                    Code(value="MUB", descriptions={"en": "Mubarraz"}),
                                    Code(value="UL", descriptions={"en": "Umm-Lulu"}),
                                    Code(value="SOK", descriptions={"en": "Sokol"}),
                                    Code(value="EB", descriptions={"en": "Espo-B"}),
                                    Code(value="SAKB", descriptions={"en": "Sakhal-B"}),
                                    Code(value="COL", descriptions={"en": "Coldlake"}),
                                    Code(value="WTIM", descriptions={"en": "WTIM"}),
                                    Code(value="EF", descriptions={"en": "Egl-Ford"}),
                                    Code(value="MARS", descriptions={"en": "Mars"}),
                                    Code(value="WTL", descriptions={"en": "WTL"}),
                                    Code(value="UC", descriptions={"en": "UTICA-C"}),
                                    Code(value="MAYA", descriptions={"en": "Maya"}),
                                    Code(value="CASB", descriptions={"en": "Castla-B"}),
                                    Code(value="ORI", descriptions={"en": "Oriente"}),
                                    Code(value="NAPO", descriptions={"en": "Napo"}),
                                    Code(value="SAHB", descriptions={"en": "Sahara-B"}),
                                    Code(value="AMNA", descriptions={"en": "Amna"}),
                                    Code(value="BA", descriptions={"en": "Bu Attfl"}),
                                    Code(value="EBO", descriptions={"en": "EBOME"}),
                                    Code(value="OGU", descriptions={"en": "Oguendjo"}),
                                    Code(value="OLO", descriptions={"en": "Olombend"}),
                                    Code(value="WAN", descriptions={"en": "Wandoo"}),
                                    Code(value="WHT", descriptions={"en": "WHTSTN-C"}),
                                    Code(value="ICH", descriptions={"en": "ICHTHY-C"}),
                                    Code(value="PF", descriptions={"en": "Papua-FO"})],
                                names={"en": "Oil Type"})],
            concepts=[concepts["UNIT"],
                      concepts["FREQ"],
                      Concept(id="OILTYPE", names={"en": "Oil Type"})],
            dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                        Dimension(concept_id="OILTYPE", codelist_id="CL_OILTYPE")],
            id="COIbOT",
            names={"en": "Crude Oil Import by Oil Type"})],
    "05": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   codelists["CL_COUNTRY"]],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  concepts["COUNTRY"]],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="COUNTRY", codelist_id="CL_COUNTRY")],
        id="COSbS",
        names={"en": "Crude Oil Shipment by Source (non-Refining Use)"})],
    "06": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   codelists["CL_INDEX"]],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  concepts["INDEX"]],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="INDEX", codelist_id="CL_INDEX")],
        id="SDLPG",
        names={"en": "Supply and Demand of LPG"})],
    "07": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   codelists["CL_PRODUCT"],
                   codelists["CL_CURRENCY"]],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  concepts["PRODUCT"],
                  concepts["CURRENCY"]],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="CURRENCY", codelist_id="CL_CURRENCY"),
                    Dimension(concept_id="PRODUCT", codelist_id="CL_PRODUCT")],
        id="OIP",
        names={"en": "Oil Import Price"})],
    "09": [DatasetStructure(
        attributes=[attributes['UNIT']],
        codelists=[codelists["CL_UNIT"],
                   codelists["CL_FREQ"],
                   CodeList(id="CL_STOCKTARGET",
                            codes=[Code(value="CO", descriptions={"en": "Crude oil"}),
                                   Code(value="P", descriptions={"en": "Products"}),
                                   Code(value="D", descriptions={"en": "Days"})],
                            names={"en": "Stock target"}),
                   CodeList(id="CL_SUBJECT",
                            codes=[Code(value="P", descriptions={"en": "Private"}),
                                   Code(value="G", descriptions={"en": "Government"}),
                                   Code(value="JOSP",
                                        descriptions={
                                            "en": "Joint oil storage projects"})],
                            names={"en": "Stock subject"})],
        concepts=[concepts["UNIT"],
                  concepts["FREQ"],
                  Concept(id="STOCKTARGET", names={"en": "Stock target"}),
                  Concept(id="SUBJECT", names={"en": "Stock subject"})],
        dimensions=[Dimension(concept_id="FREQ", codelist_id="CL_FREQ"),
                    Dimension(concept_id="SUBJECT", codelist_id="CL_SUBJECT"),
                    Dimension(concept_id="STOCKTARGET", codelist_id="CL_STOCKTARGET")],
        id="OS",
        names={"en": "Oil Stockpiling"})]
}

REGEXS = {
    'period_monthly': r'^(\d{4})[\.\s]+(\d{1,2})$',
    'period_only_month': r'^(\d{1,2})$',
}

log = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--log', default='WARNING', help='level of logging messages')
    add_arguments_for_convert(parser)
    args = parser.parse_args()

    setup_logging(args)

    source_dir = args.source_dir
    if not source_dir.exists():
        parser.error("Source input_dir {!r} not found".format(str(source_dir)))

    target_dir = args.target_dir
    if not target_dir.exists():
        parser.error("Target input_dir {!r} not found".format(str(target_dir)))

    nb_expected_datasets = 0
    errors_artifact = ErrorsArtifact()
    for dir, datasetStructures in DATASETS_DEFINITIONS.items():
        for datasetStructure in datasetStructures:
            nb_expected_datasets += 1
            dataset_code = datasetStructure.id
            dataset_dir = target_dir / dataset_code
            try:
                convert_dataset(source_dir / dir, datasetStructure, dataset_dir)
            except Exception as e:
                if getattr(args, 'stop-on-exceptions', None):
                    raise e
                log.warning("{!r} dataset aborted ! - {}".format(dataset_code, e))
                # Add error to artifacts
                errors_artifact.add_dataset_error(dataset_code, e)
                # Delete dataset input_dir
                shutil.rmtree(dataset_dir)
                continue

    # provider.json
    write_json_file(target_dir / 'provider.json', PROVIDER_DATA)

    return 0


def parse_cell(sheet, row, coll):
    cell_val = sheet.cell(row, coll).value
    cell_val = NAN if cell_val == '-' or not cell_val \
        else re.sub(r'[^0-9\.\,]', '', '%s' % cell_val)
    return parse_observation_value(cell_val)


def convert_dataset(input_dir: Path, structure: DatasetStructure, output_dir: Path):
    output_dir.mkdir(exist_ok=True, parents=True)
    dataset_source_xls = \
        sorted(input_dir.glob("*"), key=os.path.basename, reverse=True)[0]
    dataset_source = xlrd.open_workbook(dataset_source_xls, on_demand=True)
    series_dict = {}
    curr_year = [None]

    def match_date(cell, c_year):
        val = '%02d' % cell.value if cell.ctype == 2 else cell.value
        match = re.match(REGEXS['period_monthly'], '%s' % val)
        match_month = re.match(REGEXS['period_only_month'], '%s' % val)
        if match or match_month:
            month = '%02d' % int(match.group(2) if match else match_month.group(1))
            if match:
                c_year[0] = match.group(1)
            return c_year[0] + '-' + month

    def add_obs_by_mapping(sheet, cells_mapping, concept_id):
        for row_index, source_cell in enumerate(sheet.col(1)):
            observation_time = match_date(source_cell, curr_year) \
                if source_cell.value else None
            if observation_time:
                for coll_index, m_val in cells_mapping.items():
                    key = 'M.' + m_val
                    if not series_dict.get(key, None):
                        series_dict[key] = Series(key=[
                            Value(concept_id='FREQ', value='M'),
                            Value(concept_id=concept_id, value=m_val)
                        ], attributes=[Value(concept_id='UNIT', value='kl')],
                            observations=[])
                    observation = Obs(time=observation_time, attributes=[],
                                      value=parse_cell(sheet, row_index, coll_index))
                    series_dict[key].observations.append(observation)

    if structure.id == 'SDCO':
        source_sheet = dataset_source.sheet_by_index(0)
        index_codes = structure.get_codelist('CL_INDEX').codes
        series_dict = {'M.' + c.value: Series(key=[
            Value(concept_id='FREQ', value='M'),
            Value(concept_id='INDEX', value=c.value),
        ], attributes=[Value(concept_id='UNIT', value='kl')], observations=[])
            for c in index_codes}
        for r_index, cell in enumerate(source_sheet.col(0)):
            match = re.match(REGEXS['period_monthly'], cell.value)
            if match:
                obs_time = match.group(1) + '-' + match.group(2)
                for c_index, index_code in enumerate(index_codes):
                    obs = Obs(time=obs_time, attributes=[],
                              value=parse_cell(source_sheet, r_index, c_index + 1))
                    series_dict['M.' + index_code.value].observations.append(obs)
    elif structure.id == 'SaDoPP':
        index_codes = ["P", "I", "S", "E", "ES"]
        col_mapping = {1: "G", 2: "N", 3: "JF", 4: "K", 5: "GO", 6: "FOA", 7: "FOBC",
                       10: "LO", 11: "A", 12: "P"}
        for sheet_index, index_code in enumerate(index_codes):
            source_sheet = dataset_source.sheet_by_index(sheet_index)
            for r_index, cell in enumerate(source_sheet.col(0)):
                obs_time = match_date(cell, curr_year) if cell.value else None
                if obs_time:
                    for c_index, product_code in col_mapping.items():
                        series_key = 'M.%s.%s' % (index_code, product_code)
                        if not series_dict.get(series_key, None):
                            series_dict[series_key] = Series(key=[
                                Value(concept_id='FREQ', value='M'),
                                Value(concept_id='INDEX', value=index_code),
                                Value(concept_id='PRODUCT', value=product_code)
                            ], attributes=[
                                Value(concept_id='UNIT',
                                      value=('kl' if product_code not in ["A", "P"]
                                             else 'ton'))],
                                observations=[])
                        obs = Obs(time=obs_time, attributes=[],
                                  value=parse_cell(source_sheet, r_index, c_index))
                        series_dict[series_key].observations.append(obs)
    elif structure.id == 'PIbC':
        mapping = {'G': {1: 'KR', 2: 'CH', 4: 'SG', 6: 'AE', 7: 'PL', 8: 'US'},
                   'N': {1: 'KR', 2: 'TW', 3: 'HK', 5: 'TH', 6: 'SG', 7: 'MY',
                         8: 'ID', 10: 'IN', 11: 'PK', 12: 'LK', 14: 'BH',
                         15: 'SA', 16: 'KW', 17: 'QA', 18: 'AE', 20: 'NO',
                         21: 'ES', 22: 'RU', 23: 'GR', 25: 'US', 26: 'MX',
                         27: 'PE', 29: 'DZ', 30: 'EG', 32: 'AU', 33: 'PG'},
                   'K': {1: 'KR', 2: 'CH', 4: 'MY'},
                   'GO': {1: 'KR'},
                   'FOA': {1: 'KR'},
                   'FOBC': {1: 'KR', 2: 'TW', 4: 'SG', 5: 'MY', 7: 'RU', 8: 'PG'}}
        sheet_index = 0
        for product_code, c_mapping in mapping.items():
            source_sheet = dataset_source.sheet_by_index(sheet_index)
            sheet_index += 1
            series_key = 'M.%s.' % product_code
            for r_index, cell in enumerate(source_sheet.col(0)):
                obs_time = match_date(cell, curr_year) if cell.value else None
                if obs_time:
                    for c_index, country_code in c_mapping.items():
                        country_key = series_key + country_code
                        if not series_dict.get(country_key, None):
                            series_dict[country_key] = Series(key=[
                                Value(concept_id='FREQ', value='M'),
                                Value(concept_id='PRODUCT', value=product_code),
                                Value(concept_id='COUNTRY', value=country_code)
                            ], attributes=[Value(concept_id='UNIT', value='kl')],
                                observations=[])
                        obs = Obs(time=obs_time, attributes=[],
                                  value=parse_cell(source_sheet, r_index, c_index))
                        series_dict[country_key].observations.append(obs)
                elif curr_year[0]:
                    break
    elif structure.id == 'COIbC':
        source_sheet = dataset_source.sheet_by_index(0)
        mapping = {2: 'KZ', 3: 'VN', 4: 'MY', 5: 'BN', 6: 'ID', 8: 'IR', 9: 'IQ',
                   10: 'BH', 11: 'SA', 12: 'KW', 13: 'QA', 14: 'OM', 15: 'AE.',
                   17: 'RU', 18: 'CA', 19: 'US', 21: 'MX', 22: 'CO', 23: 'EC', 25: 'DZ',
                   26: 'LY', 27: 'CM', 28: 'GA', 29: 'AO', 31: 'AU', 32: 'PG'}
        add_obs_by_mapping(source_sheet, mapping, 'COUNTRY')
    elif structure.id == 'COIbOT':
        source_sheet = dataset_source.sheet_by_index(1)
        mapping = {2: "CB", 3: "BH", 4: "DH", 5: "RUB", 6: "SUT", 7: "CS", 9: "DUL",
                   10: "PB", 11: "SEP", 12: "MF", 13: "BER", 14: "BF", 16: "LS",
                   17: "CHA", 19: "SL", 20: "KAJ", 21: "KET", 24: "IL", 25: "IH",
                   26: "FB", 27: "SPC", 28: "SOR", 30: "BASL", 31: "BASH", 33: "BAM",
                   34: "AL", 35: "AH", 36: "AM", 37: "AEL", 38: "ASL", 40: "KUW",
                   41: "KSL", 43: "Q", 44: "QM", 45: "AS", 46: "LC", 47: "DFC",
                   49: "OM", 50: "MUR", 51: "DUB", 52: "UZ", 53: "DAS", 54: "MUB",
                   55: "UL", 58: "SOK", 59: "EB", 60: "SAKB", 62: "COL", 63: "WTIM",
                   64: "EF", 65: "MARS", 66: "WTL", 67: "UC", 70: "MAYA", 71: "CASB",
                   72: "ORI", 73: "NAPO", 76: "SAHB", 77: "AMNA", 78: "BA", 80: "EBO",
                   81: "OGU", 82: "OLO", 84: "WAN", 85: "WHT", 86: "ICH", 88: "PF"}
        add_obs_by_mapping(source_sheet, mapping, 'OILTYPE')
    elif structure.id == 'COSbS':
        mapping = {2: 'VN', 3: 'ID', 5: 'SA', 6: 'AE', 10: 'GA', 11: 'UNK'}
        source_sheet = dataset_source.sheet_by_index(0)
        add_obs_by_mapping(source_sheet, mapping, 'COUNTRY')
    elif structure.id == 'SDLPG':
        source_sheet = dataset_source.sheet_by_index(0)
        index_codes = ["RP", "I", "TS", "S", "OU", "E", "TD", "ES"]
        series_dict = {'M.' + c: Series(key=[
            Value(concept_id='FREQ', value='M'),
            Value(concept_id='INDEX', value=c),
        ], attributes=[Value(concept_id='UNIT', value='ton')], observations=[])
            for c in index_codes}
        for r_index, cell in enumerate(source_sheet.col(0)):
            obs_time = match_date(cell, curr_year) if cell.value else None
            if obs_time:
                for c_index, index_code in enumerate(index_codes):
                    obs = Obs(time=obs_time, attributes=[],
                              value=parse_cell(source_sheet, r_index, c_index + 1))
                    series_dict['M.' + index_code].observations.append(obs)
    elif structure.id == 'OIP':
        mapping = {'Y': {1: 'CO', 2: 'G', 3: 'N', 4: 'K', 5: 'GO', 6: 'FOA', 7: 'FOC',
                         8: 'LPG'},
                   'D': {1: 'CO', 3: 'G', 4: 'N', 5: 'K', 6: 'GO', 7: 'FOA', 8: 'FOC',
                         9: 'LPG'}}
        sheet_index = 0
        for currency, c_mapping in mapping.items():
            source_sheet = dataset_source.sheet_by_index(sheet_index)
            sheet_index += 1
            series_key = 'M.%s.' % currency
            for r_index, cell in enumerate(source_sheet.col(0)):
                obs_time = match_date(cell, curr_year) if cell.value else None
                if obs_time:
                    for c_index, product in c_mapping.items():
                        product_key = series_key + product
                        if not series_dict.get(product_key, None):
                            unit = {'Y': 'Yen', 'D': 'Dol'}[currency] + '/' + \
                                   ('ton' if product == 'LPG' else 'kl')
                            series_dict[product_key] = Series(key=[
                                Value(concept_id='FREQ', value='M'),
                                Value(concept_id='CURRENCY', value=currency),
                                Value(concept_id='PRODUCT', value=product)
                            ], attributes=[Value(concept_id='UNIT', value=unit)],
                                observations=[])
                        obs = Obs(time=obs_time, attributes=[],
                                  value=parse_cell(source_sheet, r_index, c_index))
                        series_dict[product_key].observations.append(obs)
    elif structure.id == 'OS':
        series_dict = {'M.' + s.value + '.' + st.value: Series(key=[
            Value(concept_id='FREQ', value='M'),
            Value(concept_id='SUBJECT', value=s.value),
            Value(concept_id='STOCKTARGET', value=st.value),
        ], attributes=[Value(concept_id='UNIT', value='10k_kls')], observations=[])
            for s in structure.get_codelist('CL_SUBJECT').codes
            for st in structure.get_codelist('CL_STOCKTARGET').codes}
        source_sheet = dataset_source.sheet_by_index(0)
        mapping = {2: 'P.CO', 3: 'P.P', 5: 'P.D', 6: 'G.CO', 7: 'G.P', 9: 'G.D',
                   10: 'JOSP.CO', 12: 'JOSP.D'}
        for r_index, cell in enumerate(source_sheet.col(0)):
            obs_time = match_date(cell, curr_year) if cell.value else None
            if obs_time:
                for c_index, target_key in mapping.items():
                    obs = Obs(time=obs_time, attributes=[],
                              value=parse_cell(source_sheet, r_index, c_index))
                    series_dict['M.%s' % target_key].observations.append(obs)

    if series_dict:
        write_json_file(output_dir / 'dataset.json',
                        {**structure_to_dataset_json(dataset_code=structure.id,
                                                     structure=structure,
                                                     lang_candidates=["en"],
                                                     all_series=list(
                                                         series_dict.values())),
                         'updated_at': dataset_source_xls.name.split('_')[0]})
        write_jsonl_file(output_dir / 'series.jsonl',
                         [series_to_series_json(s) for s in series_dict.values()])


def write_json_file(file_path: Path, data):
    """Writes data the JSON way to file_path"""

    with file_path.open('w', encoding='utf-8') as json_fd:
        json.dump(data, json_fd, ensure_ascii=False, indent=2, sort_keys=True)


def write_jsonl_file(file_path: Path, data: Sequence):
    """Writes data the JSON way to file_path"""

    with file_path.open('w', encoding='utf-8') as json_fd:
        for entry in data:
            json.dump(entry, json_fd, ensure_ascii=False, sort_keys=True)
            json_fd.write('\n')


if __name__ == '__main__':
    sys.exit(main())
